### ISSUE TITLE
Is base64 encoding valid?

### ISSUE THREAD

**Issue by johnny-mh** [chiefbiiko/hmac#4]
Hi!

I've tested some hashing with NodeJS 'crypto' and this module. and I found some difference.

### NODEJS

```nodejs
import { createHmac } from 'crypto';

const hmac = createHmac('sha1', 'a_b');
hmac.update('c_d');
console.log(hmac.digest('base64'));
```

result: `74JmntqkXKD8iUERSZu+Kq98Zco=`

### DENO

```deno
import { hmac } from 'https://denopkg.com/chiefbiiko/hmac/mod.ts'

console.log(hmac('sha1', 'a_b', 'c_d', 'utf8', 'base64'));
```

result: `74JmntqkXKD8iUERSZu-Kq98Zco=`

According to https://en.wikipedia.org/wiki/Base64. character `-` is not allowed. but this module make this character.

Is something wrong with my code?

**Comment by johnny-mh** [comment]
I've found there is options for URL and filename. https://www.base64encoder.io/learn/#base64-encoding-with-url-and-filename-safe-alphabets.

So I replace that simply.

Would you support this situations?

**Comment by cedricpoon** [comment]
I am facing exactly the same issue. I would like to add that `openssl` (LibreSSL 2.8.3 on macOS) also hashes return with `+` and `/`. `openssl` should be authority enough to indicate the necessity of supporting `+` and `/`.

**Comment by ThePrimeagen** [comment]
So I am betwixt a rock and a hard place right now.  I have a very successful crypto trading platform in which is being rewritten for deno, the securest, most performant, and modern typescript environment ever created by man.  With such leaps in technology comes great responsibility in early contributors such as your fine selves.  I, unfortunately, am burdened with the task of Base64 decoding my financial freedom with deno.  

Alas and alak, after several attempts at encoding both atob and decode have failed me.  Now I am left with only one option, which is to use node.  Next thing you know, the Chinese will be stealing all my cryptos with such an insecure and poorly thought through environment, such as the aforementioned node.

Shall my dream of a lambo and a peach polo with the gold chains  die cause of a base64 decoding issue?   I sure hope not.  Thank you for making such a swell and thoughtful package and might I say, a well coded one too.  Thanks.  God bless.   Sayonara.

PS. my + is turning into a -, which is very negative and I don't subscribe to that anti Tony Robbins bullshit.

**Comment by ghost** [comment]
So I am betwixt a rock and a hard place right now. I have a very successful crypto trading platform in which is being rewritten for deno, the securest, most performant, and modern typescript environment ever created by man. With such leaps in technology comes great responsibility in early contributors such as your fine selves. I, unfortunately, am burdened with the task of Base64 decoding my financial freedom with deno.

Alas and alak, after several attempts at encoding both atob and decode have failed me. Now I am left with only one option, which is to use node. Next thing you know, the Chinese will be stealing all my cryptos with such an insecure and poorly thought through environment, such as the aforementioned node.

Shall my dream of a lambo and a peach polo with the gold chains die cause of a base64 decoding issue? I sure hope not. Thank you for making such a swell and thoughtful package and might I say, a well coded one too. Thanks. God bless. Sayonara.

PS. my + is turning into a -, which is very negative and I don't subscribe to that anti Tony Robbins bullshit.

**Comment by johnny-mh** [comment]
@ThePrimeagen So what do you want to say? 🤔

**Comment by chiefbiiko** [comment]
@johnny-mh sorry 4 the long wait
`hmac@v2.0.0` 's base64 digest encoding defaults to the standard alphabet - not the urlsafe variant
its hashes are now comparable with those of other platforms/modules
