### ISSUE TITLE
Deno land version not bumped

### ISSUE THREAD

**Issue by LuisMayo** [chiefbiiko/hmac#6]
Last version available in Deno Land is still 1.0.2 It'd be cool to have v2.0.0 there ^^
https://deno.land/x/hmac@v1.0.2

**Comment by chiefbiiko** [comment]
thanks for the report
what do i have to do to republish there?

**Comment by LuisMayo** [comment]
I'm not sure as I've never published to deno.land. But I think you need to define a webhook on the repository that will trigger whenever a new tag is pushed.

Check this
https://deno.land/posts/registry2

**Comment by chiefbiiko** [comment]
here is the new denoland version >> https://deno.land/x/hmac@v2.0.1/mod.ts
